#!/bin/bash

JAVA_OPTS="\
-Dorg.jboss.logging.provider=slf4j \
-Xmx2G \
-XX:+UseG1GC -XX:MaxGCPauseMillis=200 \
"

DIR=$(cd `dirname $0`/.. && pwd)

# These values should generated by the plugin in config.sh:
#
# PROJECT=
# VERSION=
# MAIN_CLASS=
source $DIR/bin/config.sh

PID_FILE="$DIR/$PROJECT-$VERSION.pid"
CONF_DIR="$DIR/conf"
LIB_DIR="$DIR/lib"
JAR_FILE="$DIR/$PROJECT-$VERSION.jar"

status () {
    if [ -f $PID_FILE ]; then
        echo "Server is started as pid `cat $PID_FILE`."
    else
        echo "Server is not started."
    fi
}

start () {
    if [ -f $PID_FILE ]; then
        echo "Application has already started as pid `cat $PID_FILE`!"
        exit 1
    fi

    cd $DIR
    nohup java $JAVA_OPTS -cp "$CONF_DIR:$LIB_DIR/*:$JAR_FILE" $MAIN_CLASS &
    echo $! > $PID_FILE
    echo "Server started as pid `cat $PID_FILE`"
}

stop () {
    if [ -f $PID_FILE ]; then
        pid=`cat $PID_FILE`
        kill `cat $PID_FILE`
        rm $PID_FILE
        echo "Killed pid $pid"
    else
        echo "Server is not started!"
    fi
}

restart () {
    if [ -f $PID_FILE ]; then
        stop
    fi
    start
}

help () {
    echo "Usage: server.sh start|stop|restart|status"
}

case $1 in
	start) start ;;
	stop) stop ;;
	restart) restart ;;
	status) status ;;
	*) help ;;
esac
